export const extendedCuratedProfiles = {
  alternative: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/ɔːlˈtɜːnətɪv/',
    cefr: 'B2',
    level: '核心输出词',
    value: 85,
    skills: { reading: 85, listening: 71, task1: 57, task2: 91, speaking: 78 },
    coreMeaning: '替代方案；可取代当前选择的另一种办法或事物。',
    definition: 'something that can be chosen or used instead of something else',
    register: '中性 / 正式',
    topics: ['交通', '能源', '消费'],
    patterns: ['an alternative to + noun / -ing', 'an alternative way to + verb', 'alternative + noun'],
    collocations: [
      { phrase: 'a viable alternative to', meaning: '可行的替代方案', use: '提出对策' },
      { phrase: 'alternative energy sources', meaning: '替代能源', use: '环境、能源' },
      { phrase: 'an alternative to private cars', meaning: '私家车的替代方式', use: '交通话题' },
    ],
    distinctions: [
      { word: 'option', difference: 'option 是可选项；alternative 强调可替代原有事物的另一种选择。', rule: '需要突出“替代 X”时用 an alternative to X。' },
    ],
    pitfalls: [
      { wrong: 'an alternative of driving', better: 'an alternative to driving', why: 'alternative 后表达被替代对象时用 to。' },
    ],
    writingTip: '提出 alternative 时，要说明它为何可负担、便利或可实施。',
    speakingTip: '谈通勤时，public transport is a practical alternative to driving 很自然。',
    recall: '“私家车的可行替代方案”怎么说？',
    answer: 'a viable alternative to private cars',
    productionFrame: 'Public transport is a viable alternative to private cars.',
  },
  inescapable: {
    quality: 'curated',
    confidence: 4,
    ipaUk: '/ˌɪnɪˈskeɪpəbl/',
    cefr: 'C1',
    level: '理解优先词',
    value: 68,
    skills: { reading: 86, listening: 58, task1: 35, task2: 72, speaking: 52 },
    coreMeaning: '不可避免的；无法逃避、摆脱或回避的。',
    definition: 'impossible to avoid or escape from',
    register: '正式 / 强调语气',
    topics: ['科技', '社会变化', '工作'],
    patterns: ['an inescapable consequence of + noun', 'be inescapable', 'seem inescapable'],
    collocations: [
      { phrase: 'an inescapable consequence', meaning: '不可避免的后果', use: '因果论证' },
      { phrase: 'an inescapable part of life', meaning: '生活中无法避免的一部分', use: '社会、个人话题' },
      { phrase: 'seem inescapable', meaning: '似乎无法避免', use: '审慎判断' },
    ],
    distinctions: [
      { word: 'inevitable', difference: 'inevitable 强调某事必然发生；inescapable 更强调无法摆脱某处境或后果。', rule: '证据不足时不要把 merely likely 的结果写成 inescapable。' },
    ],
    pitfalls: [
      { wrong: 'inescapable to avoid', better: 'inescapable / impossible to avoid', why: 'inescapable 本身已经含有“无法避免”的意思。' },
    ],
    writingTip: '不是必需的高分词；只有确实要强调无法回避的后果时才使用。',
    speakingTip: '日常表达中 difficult to avoid 或 inevitable 往往更自然。',
    recall: '“不可避免的后果”怎么说？',
    answer: 'an inescapable consequence',
    productionFrame: 'X may be an inescapable consequence of Y.',
  },
  uniform: {
    quality: 'curated',
    confidence: 4,
    ipaUk: '/ˈjuːnɪfɔːm/',
    cefr: 'B2',
    level: '多义核心词',
    value: 72,
    skills: { reading: 82, listening: 65, task1: 71, task2: 69, speaking: 64 },
    coreMeaning: '一致的、统一的；也指学校、工作等场合的制服。',
    definition: 'the same in all parts, or a set of standard clothes worn by a group',
    register: '中性 / 正式',
    topics: ['教育', '数据', '职场'],
    patterns: ['wear a uniform', 'be uniform across + noun', 'a uniform standard for + noun'],
    collocations: [
      { phrase: 'a school uniform', meaning: '校服', use: '教育话题' },
      { phrase: 'a uniform standard', meaning: '统一标准', use: '政策、服务' },
      { phrase: 'uniform distribution', meaning: '均匀分布', use: '数据、科学' },
    ],
    distinctions: [
      { word: 'consistent', difference: 'uniform 强调各部分相同；consistent 强调前后一致或稳定，不一定完全相同。', rule: '各地区或数值完全一致才用 uniform。' },
    ],
    pitfalls: [
      { wrong: 'students must wear uniform', better: 'students must wear a uniform / uniforms', why: '表示一套制服时需要冠词；泛指多名学生时可用复数 uniforms。' },
    ],
    writingTip: '描述数据时，不要因为少数数值相近就断言整体 uniform。',
    speakingTip: '学校制服是最自然、最常用的输出场景。',
    recall: '“各年龄组的模式并不一致”怎么说？',
    answer: 'The pattern was not uniform across all age groups.',
    productionFrame: 'The pattern was not uniform across all age groups.',
  },
  contact: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/ˈkɒntækt/ n.; /kənˈtækt/ v.',
    cefr: 'B1–B2',
    level: '多义核心词',
    value: 82,
    skills: { reading: 86, listening: 78, task1: 51, task2: 76, speaking: 87 },
    coreMeaning: '联系、接触；也可作动词表示与某人取得联系。',
    definition: 'communication with someone, or the act of communicating with someone',
    register: '中性 / 正式',
    topics: ['科技', '工作', '人际关系'],
    patterns: ['be / stay in contact with + person', 'contact sb about + noun', 'have physical contact with + noun'],
    collocations: [
      { phrase: 'maintain contact with', meaning: '保持联系', use: '人际、科技' },
      { phrase: 'make contact with', meaning: '取得联系', use: '工作、正式沟通' },
      { phrase: 'close contact with', meaning: '密切接触', use: '健康、人际' },
    ],
    distinctions: [
      { word: 'communicate', difference: 'communicate 强调信息交流过程；contact 强调建立或保持连接，也可只是单向联系。', rule: '第一次联系某人用 contact；讨论双向交流质量用 communicate。' },
    ],
    pitfalls: [
      { wrong: 'contact with me if you need help', better: 'contact me if you need help / get in contact with me', why: 'contact 作动词时直接接宾语，不接 with。' },
    ],
    writingTip: '科技题中可用 stay in contact with，但要说明它如何影响关系质量。',
    speakingTip: 'keep in touch 与 stay in contact with 都很自然，后者稍正式。',
    recall: '“与老朋友保持联系”怎么说？',
    answer: 'stay in contact with old friends',
    productionFrame: 'Technology helps people stay in contact with Y.',
  },
  determine: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/dɪˈtɜːmɪn/',
    cefr: 'B2',
    level: '核心输出词',
    value: 87,
    skills: { reading: 88, listening: 68, task1: 58, task2: 92, speaking: 68 },
    coreMeaning: '决定、影响结果；也指通过调查确定事实。',
    definition: 'to control or decide something, or to discover the facts about something',
    register: '正式 / 学术',
    topics: ['教育', '健康', '研究'],
    patterns: ['determine + noun', 'determine whether + clause', 'be determined by + noun'],
    collocations: [
      { phrase: 'determine the outcome', meaning: '决定结果', use: '因果分析' },
      { phrase: 'determine whether + clause', meaning: '确定是否……', use: '研究、决策' },
      { phrase: 'be determined by', meaning: '由……决定', use: '学术论证' },
    ],
    distinctions: [
      { word: 'decide', difference: 'decide 通常是人有意识地作选择；determine 表示因素决定结果，或查明事实。', rule: '委员会 decide；收入、机会或环境 determine 某种结果。' },
    ],
    pitfalls: [
      { wrong: 'determine about the cause', better: 'determine the cause', why: 'determine 作“确定”时通常直接接宾语。' },
    ],
    writingTip: '因果论证中少用绝对语气；复杂结果常用 largely determined by。',
    speakingTip: '可用于解释影响因素：Price often determines what people buy。',
    recall: '“获得教育的机会很大程度上由收入决定”怎么说？',
    answer: 'Access to education is largely determined by income.',
    productionFrame: 'Access to Y is largely determined by X.',
  },
  vary: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/ˈveəri/',
    cefr: 'B2',
    level: 'Task 1 必备词',
    value: 92,
    skills: { reading: 86, listening: 68, task1: 98, task2: 78, speaking: 71 },
    coreMeaning: '不同、变化；常描述数值在群体、地点或条件之间存在差异。',
    definition: 'to be different in size, amount, or level according to the situation',
    register: '中性 / 数据描述',
    topics: ['图表', '气候', '教育'],
    patterns: ['vary from A to B', 'vary according to + noun', 'vary considerably'],
    collocations: [
      { phrase: 'vary considerably', meaning: '差异很大', use: '数据比较' },
      { phrase: 'vary from region to region', meaning: '因地区而异', use: '社会、地理' },
      { phrase: 'vary according to age', meaning: '因年龄而异', use: '人口数据' },
    ],
    distinctions: [
      { word: 'change', difference: 'change 强调随时间变成不同；vary 强调不同群体、地点或条件之间有差异。', rule: '横向比较用 vary；单一趋势随时间上升或下降常用 change、rise、fall。' },
    ],
    pitfalls: [
      { wrong: 'vary between 10% to 20%', better: 'vary between 10% and 20% / vary from 10% to 20%', why: 'between 与 and 配对；from 与 to 配对。' },
    ],
    writingTip: '写 vary 时说明差异维度，如 age、region 或 income level。',
    speakingTip: '谈偏好时可说 preferences vary from person to person。',
    recall: '“比率因地区而异”怎么说？',
    answer: 'Rates vary from region to region.',
    productionFrame: 'Rates vary considerably from one region to another.',
  },
  essential: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/ɪˈsenʃl/',
    cefr: 'B2',
    level: '核心输出词',
    value: 86,
    skills: { reading: 84, listening: 73, task1: 55, task2: 91, speaking: 80 },
    coreMeaning: '必不可少的；对某项目标或功能极其重要的。',
    definition: 'necessary or extremely important',
    register: '中性 / 正式',
    topics: ['教育', '健康', '公共服务'],
    patterns: ['be essential for + noun / -ing', 'it is essential that + clause', 'an essential part of + noun'],
    collocations: [
      { phrase: 'essential skills', meaning: '必备技能', use: '教育、就业' },
      { phrase: 'essential services', meaning: '基本公共服务', use: '政府、社会' },
      { phrase: 'an essential part of', meaning: '……不可或缺的一部分', use: '论证' },
    ],
    distinctions: [
      { word: 'important', difference: 'important 表示重要；essential 表示缺少它会妨碍目标或功能实现。', rule: '只有确实不可或缺时才用 essential，避免夸大。' },
    ],
    pitfalls: [
      { wrong: 'essential of success', better: 'essential for success / essential to success', why: 'essential 通常搭配 for 或 to，不搭配 of。' },
    ],
    writingTip: '用 essential 后说明为什么不可缺少，能避免空泛的强烈判断。',
    speakingTip: 'Sleep is essential for my concentration 是自然的个人化表达。',
    recall: '“政府确保基本服务至关重要”怎么说？',
    answer: 'It is essential for governments to ensure essential services.',
    productionFrame: 'It is essential for governments to ensure Y.',
  },
  attempt: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/əˈtempt/',
    cefr: 'B2',
    level: '核心输出词',
    value: 79,
    skills: { reading: 81, listening: 66, task1: 45, task2: 84, speaking: 65 },
    coreMeaning: '尝试；为实现某目标所作的努力。',
    definition: 'an effort to do something, or to try to do something',
    register: '中性 / 正式',
    topics: ['政策', '教育', '研究'],
    patterns: ['attempt to + verb', 'make an attempt to + verb', 'an attempt to + verb'],
    collocations: [
      { phrase: 'make an attempt to', meaning: '尝试做……', use: '正式叙述' },
      { phrase: 'an attempt to reduce X', meaning: '减少 X 的尝试', use: '政策、环境' },
      { phrase: 'a failed attempt', meaning: '失败的尝试', use: '评价措施' },
    ],
    distinctions: [
      { word: 'try', difference: 'try 更口语、最通用；attempt 更正式，常突出有难度或未必成功的努力。', rule: '写政策或研究行动可用 attempt；日常口语通常用 try。' },
    ],
    pitfalls: [
      { wrong: 'attempt doing something', better: 'attempt to do something', why: 'attempt 后通常接 to + 动词原形。' },
    ],
    writingTip: '提到 attempt 后，最好交代成效或限制，避免把“尝试”误写成“解决”。',
    speakingTip: '描述个人经历时 try 往往更自然，除非想强调难度。',
    recall: '“该政策是减少污染的一次尝试”怎么说？',
    answer: 'The policy is an attempt to reduce pollution.',
    productionFrame: 'The policy is an attempt to reduce X.',
  },
  form: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/fɔːm/',
    cefr: 'B1–B2',
    level: '多义核心词',
    value: 82,
    skills: { reading: 88, listening: 70, task1: 83, task2: 75, speaking: 70 },
    coreMeaning: '形式、形态；也可作动词表示形成或构成。IELTS 中常用 take the form of。',
    definition: 'a type or shape of something; to make or develop something',
    register: '中性 / 正式',
    topics: ['图表', '教育', '科技'],
    patterns: ['take the form of + noun', 'form + noun', 'be formed from / by + noun'],
    collocations: [
      { phrase: 'take the form of', meaning: '采取……形式', use: '说明、分类' },
      { phrase: 'form part of', meaning: '构成……的一部分', use: '正式论述' },
      { phrase: 'a common form of', meaning: '常见的一种形式', use: '定义、举例' },
    ],
    distinctions: [
      { word: 'shape', difference: 'shape 主要指物体外形；form 更广，可指方式、类型或抽象表现。', rule: '沟通、支持、能源等抽象“形式”用 form。' },
    ],
    pitfalls: [
      { wrong: 'in a form of financial support', better: 'in the form of financial support', why: '表示“以……的形式”时通常使用固定结构 in the form of。' },
    ],
    writingTip: '用 take the form of 具体化抽象措施，例如资金支持、培训或法规。',
    speakingTip: '可说 reading is a form of relaxation，简洁自然。',
    recall: '“援助以资金支持的形式提供”怎么说？',
    answer: 'The assistance takes the form of financial support.',
    productionFrame: 'The assistance takes the form of X.',
  },
  lead: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/liːd/ v.; /led/ n.',
    cefr: 'B1–B2',
    level: '多义核心词',
    value: 90,
    skills: { reading: 90, listening: 77, task1: 70, task2: 95, speaking: 82 },
    coreMeaning: '导致、引导；IELTS 中最重要的是 lead to 表示因果结果。',
    definition: 'to cause something to happen, or to guide someone somewhere',
    register: '中性 / 正式',
    topics: ['健康', '教育', '社会问题'],
    patterns: ['lead to + noun / -ing', 'lead sb to + verb', 'lead the way in + -ing'],
    collocations: [
      { phrase: 'lead to an increase in', meaning: '导致……增加', use: 'Task 1、因果' },
      { phrase: 'lead to better outcomes', meaning: '带来更好结果', use: '教育、政策' },
      { phrase: 'lead the way in', meaning: '在……方面领先', use: '科技、政府' },
    ],
    distinctions: [
      { word: 'cause', difference: 'cause 往往强调直接造成，常用于负面结果；lead to 强调结果链条，可用于正负两面。', rule: '因果不绝对时用 can / may lead to，使表述更审慎。' },
    ],
    pitfalls: [
      { wrong: 'lead to do better', better: 'lead to better results / lead to doing better', why: '因果结构 lead to 中的 to 是介词，后接名词或 -ing。' },
    ],
    writingTip: '因果句中优先使用 can lead to 或 may lead to，避免证据不足的绝对断言。',
    speakingTip: '谈习惯后果时可自然说 too much screen time can lead to poor sleep。',
    recall: '“导致成本增加”怎么说？',
    answer: 'lead to an increase in costs',
    productionFrame: 'X can lead to an increase in Y.',
  },
  figure: {
    quality: 'curated',
    confidence: 5,
    ipaUk: '/ˈfɪɡə(r)/',
    cefr: 'B1–B2',
    level: 'Task 1 必备词',
    value: 90,
    skills: { reading: 82, listening: 65, task1: 98, task2: 67, speaking: 59 },
    coreMeaning: '数字、统计数值；Task 1 中常指某项数据。',
    definition: 'a number, especially one representing an amount or statistic',
    register: '中性 / 数据描述',
    topics: ['图表', '人口', '经济'],
    patterns: ['the figure for + noun', 'a figure of + number', 'reach / stand at + figure'],
    collocations: [
      { phrase: 'the figure for X', meaning: 'X 的数据', use: 'Task 1 主语' },
      { phrase: 'a figure of 30%', meaning: '30% 这一数值', use: '数据报告' },
      { phrase: 'official figures', meaning: '官方数据', use: '政府、研究' },
    ],
    distinctions: [
      { word: 'number', difference: 'number 是一般的数字或数量；figure 常指报告、图表或统计中的具体数值。', rule: 'Task 1 可用 the figure for unemployment；数人数时常用 the number of people。' },
    ],
    pitfalls: [
      { wrong: 'the figures was 20%', better: 'the figure was 20% / the figures were ...', why: 'figure 是单数，figures 是复数，动词必须对应。' },
    ],
    writingTip: '与 percentage、proportion 交替使用，但始终明确 figure 对应的指标。',
    speakingTip: '日常对话不必刻意使用；谈数据或预算时才自然。',
    recall: '“失业率的数据上升了”怎么说？',
    answer: 'The figure for unemployment rose.',
    productionFrame: 'The figure for X rose from A to B.',
  },
};

Object.assign(extendedCuratedProfiles, {
  alter: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈɔːltə(r)/",
    cefr: "B2",
    level: "核心输出词",
    value: 82,
    skills: { reading: 80, listening: 68, task1: 55, task2: 90, speaking: 78 },
    coreMeaning: "有目的地改变已有事物的细节、形式或安排。",
    definition: "to make a deliberate change to something",
    register: "中性偏正式",
    topics: ["政策", "教育", "科技", "环境"],
    patterns: ["alter sth to reflect sth", "alter sth from A to B", "be altered by sth"],
    collocations: [
      { phrase: "alter a plan", meaning: "调整计划", use: "说明因成本或反馈而改变安排" },
      { phrase: "alter the design", meaning: "修改设计", use: "用于产品、建筑或系统" },
      { phrase: "alter the law", meaning: "修改法律", use: "用于政策和立法语境" },
    ],
    distinctions: [
      { word: "change", difference: "change 范围更广；alter 通常指对现有事物作有意调整。", rule: "用 alter 时要有明确受事，如 alter the policy。" },
    ],
    pitfalls: [
      { wrong: "alter to reduce costs", better: "alter the plan to reduce costs", why: "alter 是及物动词，通常需要宾语。" },
    ],
    writingTip: "写建议时用 alter policies to reflect current needs 很自然。",
    speakingTip: "谈个人计划可说 alter my schedule，而非生硬替换所有 change。",
    recall: "alter = deliberately make something different",
    answer: "The government should alter the policy to reflect current needs.",
    productionFrame: "Authorities should alter ___ to ___.",
  },
  focus: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈfəʊkəs/",
    cefr: "B2",
    level: "核心输出词",
    value: 92,
    skills: { reading: 89, listening: 85, task1: 65, task2: 92, speaking: 91 },
    coreMeaning: "把注意力、资源或讨论集中在某事上。",
    definition: "to give special attention to a particular thing",
    register: "中性；学术写作常用",
    topics: ["教育", "工作", "健康", "科技"],
    patterns: ["focus on sth", "focus on doing sth", "focus attention/efforts on sth"],
    collocations: [
      { phrase: "focus on the main trend", meaning: "聚焦主要趋势", use: "Task 1 概述或课堂分析" },
      { phrase: "focus resources on sth", meaning: "把资源集中于某事", use: "政策和商业讨论" },
      { phrase: "a clear focus on sth", meaning: "对某事的明确关注", use: "评价计划或课程" },
    ],
    distinctions: [
      { word: "concentrate", difference: "两者都可表“专注”；focus 更常用于计划、议题和资源。", rule: "最稳妥搭配是 focus on + 名词或动名词。" },
    ],
    pitfalls: [
      { wrong: "focus in environmental problems", better: "focus on environmental problems", why: "focus 固定搭配 on。" },
    ],
    writingTip: "Task 2 可写政策应 focus on long-term outcomes。",
    speakingTip: "回答学习习惯时，focus on doing sth 很自然。",
    recall: "focus on = give attention to",
    answer: "Schools should focus on practical skills as well as academic knowledge.",
    productionFrame: "It is important to focus on ___ rather than ___.",
  },
  demand: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/dɪˈmɑːnd/",
    cefr: "B2",
    level: "核心输出词",
    value: 93,
    skills: { reading: 91, listening: 84, task1: 90, task2: 90, speaking: 84 },
    coreMeaning: "强烈要求；或指人们想购买、使用某物的需求。",
    definition: "a strong request, or the desire for a product or service",
    register: "中性偏正式",
    topics: ["经济", "住房", "交通", "消费"],
    patterns: ["demand for sth", "demand that + clause", "demand sth from sb"],
    collocations: [
      { phrase: "growing demand for housing", meaning: "不断增长的住房需求", use: "Task 1 和城市议题" },
      { phrase: "meet the demand for sth", meaning: "满足对某物的需求", use: "讨论服务供给" },
      { phrase: "demand action from the government", meaning: "要求政府采取行动", use: "社会和环保议题" },
    ],
    distinctions: [
      { word: "need", difference: "need 强调必要性；demand 强调强烈要求或市场上的需求量。", rule: "市场语境通常用 demand for，不用 need of。" },
    ],
    pitfalls: [
      { wrong: "demand of affordable housing", better: "demand for affordable housing", why: "名词 demand 后固定接 for。" },
    ],
    writingTip: "图表中可写 rising demand for public transport。",
    speakingTip: "谈城市生活时，housing demand 是很实用的搭配。",
    recall: "demand = strongly ask for / want to buy",
    answer: "There is growing demand for affordable housing.",
    productionFrame: "Growing demand for ___ has led to ___.",
  },
  vital: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈvaɪtl/",
    cefr: "B2",
    level: "核心输出词",
    value: 85,
    skills: { reading: 86, listening: 75, task1: 50, task2: 89, speaking: 78 },
    coreMeaning: "对成功、生存或结果至关重要的。",
    definition: "extremely important or necessary",
    register: "中性偏正式",
    topics: ["健康", "教育", "环境", "城市"],
    patterns: ["be vital to/for sth", "It is vital that + clause", "play a vital role in sth"],
    collocations: [
      { phrase: "play a vital role in", meaning: "在……中发挥关键作用", use: "分析原因和影响" },
      { phrase: "be vital for public health", meaning: "对公共健康至关重要", use: "健康政策议题" },
      { phrase: "a vital source of sth", meaning: "某物的重要来源", use: "资源和能源话题" },
    ],
    distinctions: [
      { word: "essential", difference: "两者都很强；essential 更接近“不可缺少”，vital 更强调关键影响。", rule: "常用 vital to/for，后接名词或动名词。" },
    ],
    pitfalls: [
      { wrong: "vital for achieve success", better: "vital for achieving success", why: "for 后需要名词或动名词。" },
    ],
    writingTip: "不要滥用；只用于真正关键的论点。",
    speakingTip: "可说 Reliable transport is vital for city residents。",
    recall: "vital = extremely important",
    answer: "Reliable public transport is vital for urban life.",
    productionFrame: "___ is vital for ___.",
  },
  conference: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈkɒnfərəns/",
    cefr: "B2",
    level: "核心理解词",
    value: 61,
    skills: { reading: 68, listening: 70, task1: 25, task2: 45, speaking: 60 },
    coreMeaning: "人们为讨论专业议题或交流信息而举行的正式会议。",
    definition: "a formal meeting where people discuss a particular subject",
    register: "正式；职业和学术语境",
    topics: ["教育", "职业", "科技", "国际事务"],
    patterns: ["attend a conference on sth", "hold a conference", "at a conference"],
    collocations: [
      { phrase: "an international conference", meaning: "国际会议", use: "国际合作话题" },
      { phrase: "a conference on climate change", meaning: "气候变化会议", use: "环境和新闻语境" },
      { phrase: "hold a conference", meaning: "举办会议", use: "机构或政府活动" },
    ],
    distinctions: [
      { word: "meeting", difference: "meeting 范围更广且常较小；conference 通常更正式、规模更大且有明确主题。", rule: "学术或行业活动优先用 conference。" },
    ],
    pitfalls: [
      { wrong: "make a conference", better: "hold or organise a conference", why: "会议通常用 hold/organise，不用 make。" },
    ],
    writingTip: "写国际合作时可用 international conference，但不要把普通课堂讨论叫 conference。",
    speakingTip: "若没有真实经历，可谈想参加的 conference。",
    recall: "conference = formal meeting on a topic",
    answer: "She attended a conference on renewable energy.",
    productionFrame: "An international conference on ___ was held to ___.",
  },
  advent: {
    quality: 'curated',
    confidence: 4,
    ipaUk: "/ˈædvent/",
    cefr: "C1",
    level: "理解优先词",
    value: 37,
    skills: { reading: 68, listening: 40, task1: 15, task2: 42, speaking: 25 },
    coreMeaning: "某项重要事物、时代或变化的到来与开始。",
    definition: "the arrival or beginning of an important new thing or event",
    register: "正式；书面语",
    topics: ["科技", "历史", "媒体", "社会"],
    patterns: ["the advent of sth", "since the advent of sth", "with the advent of sth"],
    collocations: [
      { phrase: "the advent of the internet", meaning: "互联网的出现", use: "科技发展文章" },
      { phrase: "the advent of social media", meaning: "社交媒体的兴起", use: "媒体与社会议题" },
      { phrase: "with the advent of digital technology", meaning: "随着数字技术的出现", use: "说明时代变化" },
    ],
    distinctions: [
      { word: "arrival", difference: "arrival 可指人或普通物品到达；advent 指重大新事物或时代的开始。", rule: "advent 几乎总与抽象、重要的发展连用。" },
    ],
    pitfalls: [
      { wrong: "the advent of my friend", better: "my friend's arrival", why: "advent 不用于普通个人到达。" },
    ],
    writingTip: "只写重大变化，如 the advent of digital technology。",
    speakingTip: "口语优先用 the arrival of 或 the rise of。",
    recall: "advent = an important new thing begins",
    answer: "With the advent of the internet, access to information changed dramatically.",
    productionFrame: "With the advent of ___, ___ has changed.",
  },
  element: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈelɪmənt/",
    cefr: "B2",
    level: "核心输出词",
    value: 83,
    skills: { reading: 88, listening: 75, task1: 65, task2: 90, speaking: 74 },
    coreMeaning: "构成整体的一个部分、因素或特征。",
    definition: "one necessary part or feature of a whole",
    register: "中性偏正式",
    topics: ["教育", "社会", "科学", "环境"],
    patterns: ["an element of sth", "a key element in sth", "incorporate an element of sth"],
    collocations: [
      { phrase: "a key element of success", meaning: "成功的关键要素", use: "论证成功条件" },
      { phrase: "an essential element in education", meaning: "教育中的必要组成", use: "教育议题" },
      { phrase: "add an element of flexibility", meaning: "加入灵活性因素", use: "评价制度或计划" },
    ],
    distinctions: [
      { word: "aspect", difference: "element 是整体中的组成部分；aspect 是某事的一面或角度。", rule: "谈可构成整体的因素用 element，谈观察角度用 aspect。" },
    ],
    pitfalls: [
      { wrong: "an element for success", better: "an element of success", why: "表示“成功的组成部分”通常搭配 of。" },
    ],
    writingTip: "a key element of effective policy 是安全且自然的搭配。",
    speakingTip: "可用来解释为什么某事有效。",
    recall: "element = one part of a whole",
    answer: "Trust is a key element of a successful team.",
    productionFrame: "___ is a key element of ___.",
  },
  detail: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈdiːteɪl/",
    cefr: "B1",
    level: "核心输出词",
    value: 90,
    skills: { reading: 91, listening: 88, task1: 95, task2: 78, speaking: 85 },
    coreMeaning: "一项具体信息；也指细致地说明。",
    definition: "an individual fact or piece of information",
    register: "中性",
    topics: ["数据", "教育", "工作", "旅行"],
    patterns: ["in detail", "details of/about sth", "go into detail about sth"],
    collocations: [
      { phrase: "provide further details", meaning: "提供更多细节", use: "报告和说明" },
      { phrase: "in considerable detail", meaning: "相当详细地", use: "描述研究或经历" },
      { phrase: "a minor detail", meaning: "次要细节", use: "区分主次信息" },
    ],
    distinctions: [
      { word: "information", difference: "information 是不可数的总体信息；detail 是一条可数的具体信息。", rule: "说 a detail/two details，但不说 an information。" },
    ],
    pitfalls: [
      { wrong: "in details", better: "in detail", why: "固定表达用单数 detail。" },
    ],
    writingTip: "Task 1 先给 overview，再选择有代表性的 details。",
    speakingTip: "可说 I do not remember all the details。",
    recall: "detail = one specific piece of information",
    answer: "The report explains the proposal in detail.",
    productionFrame: "The chart provides details about ___.",
  },
  chief: {
    quality: 'curated',
    confidence: 4,
    ipaUk: "/tʃiːf/",
    cefr: "B2",
    level: "进阶理解词",
    value: 57,
    skills: { reading: 75, listening: 58, task1: 20, task2: 64, speaking: 45 },
    coreMeaning: "最重要的；或指组织中的主要负责人。",
    definition: "most important; the person in charge",
    register: "正式",
    topics: ["政策", "商业", "工作", "社会"],
    patterns: ["the chief reason for sth", "the chief aim is to do sth", "chief among sth"],
    collocations: [
      { phrase: "the chief cause of sth", meaning: "某事的主要原因", use: "因果分析" },
      { phrase: "the chief reason for sth", meaning: "某事的首要理由", use: "Task 2 论证" },
      { phrase: "a chief concern", meaning: "首要担忧", use: "政策和风险讨论" },
    ],
    distinctions: [
      { word: "main", difference: "两者都表“主要”；chief 更正式，也更强调首位或最高级别。", rule: "写作中 chief 常放在 reason、cause、aim、concern 前。" },
    ],
    pitfalls: [
      { wrong: "the chief of reason", better: "the chief reason", why: "chief 在此作形容词，直接修饰名词。" },
    ],
    writingTip: "chief reason for 是最稳妥的写作搭配。",
    speakingTip: "自然表达时可优先说 main reason。",
    recall: "chief = most important",
    answer: "The chief reason for the change was rising costs.",
    productionFrame: "The chief reason for ___ is ___.",
  },
  advance: {
    quality: 'curated',
    confidence: 4,
    ipaUk: "/ədˈvɑːns/",
    cefr: "B2",
    level: "核心输出词",
    value: 78,
    skills: { reading: 85, listening: 65, task1: 45, task2: 84, speaking: 65 },
    coreMeaning: "向前发展、推进；或指一项进步。",
    definition: "to move forward or improve; an improvement or development",
    register: "中性偏正式",
    topics: ["科技", "医学", "教育", "职业"],
    patterns: ["make an advance in sth", "advance sth by doing sth", "advance from A to B"],
    collocations: [
      { phrase: "technological advances", meaning: "技术进步", use: "科技话题" },
      { phrase: "make advances in medical research", meaning: "在医学研究上取得进展", use: "健康和科研议题" },
      { phrase: "advance an argument", meaning: "提出并推进论点", use: "正式讨论或学术写作" },
    ],
    distinctions: [
      { word: "progress", difference: "progress 通常是不可数的总体进展；advance 可作可数的具体进步，也可作动词。", rule: "说 make progress 或 make advances，不说 make an advance progress。" },
    ],
    pitfalls: [
      { wrong: "the technology is advance", better: "the technology is advanced", why: "描述“先进的”要用形容词 advanced。" },
    ],
    writingTip: "technological advances have enabled... 是自然的因果句。",
    speakingTip: "若只想表达一般进步，progress 更口语化。",
    recall: "advance = move forward / a development",
    answer: "Advances in medicine have improved life expectancy.",
    productionFrame: "Advances in ___ have enabled ___.",
  },
  maintain: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/meɪnˈteɪn/",
    cefr: "B2",
    level: "核心输出词",
    value: 88,
    skills: { reading: 90, listening: 75, task1: 80, task2: 90, speaking: 74 },
    coreMeaning: "使某物保持在同一状态或水平；坚持某一说法。",
    definition: "to keep something at the same level or condition",
    register: "中性偏正式",
    topics: ["健康", "经济", "环境", "教育"],
    patterns: ["maintain sth at a level", "maintain a balance between A and B", "maintain that + clause"],
    collocations: [
      { phrase: "maintain a balance", meaning: "维持平衡", use: "工作生活或发展议题" },
      { phrase: "maintain high standards", meaning: "保持高标准", use: "教育和服务质量" },
      { phrase: "maintain public services", meaning: "维持公共服务", use: "政府支出讨论" },
    ],
    distinctions: [
      { word: "sustain", difference: "maintain 强调保持既有状态；sustain 常强调长期支撑或使其持续。", rule: "maintain a level/standard/balance 是最安全的搭配。" },
    ],
    pitfalls: [
      { wrong: "maintain healthy", better: "maintain good health", why: "maintain 通常需要名词性宾语。" },
    ],
    writingTip: "Task 1 可写 figures remained stable or were maintained at...，注意主语是否有人为控制。",
    speakingTip: "maintain a healthy lifestyle 很自然。",
    recall: "maintain = keep at the same level",
    answer: "Governments must maintain high standards in public education.",
    productionFrame: "It is important to maintain ___ while ___.",
  },
  version: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈvɜːʃn/",
    cefr: "B1",
    level: "核心理解词",
    value: 73,
    skills: { reading: 78, listening: 75, task1: 20, task2: 45, speaking: 76 },
    coreMeaning: "某一作品、文件、产品或软件的特定形式。",
    definition: "a particular form of something, especially a document or product",
    register: "中性",
    topics: ["科技", "媒体", "教育", "消费"],
    patterns: ["a version of sth", "the latest/revised version", "an earlier version of sth"],
    collocations: [
      { phrase: "the latest version", meaning: "最新版本", use: "软件和产品讨论" },
      { phrase: "a revised version", meaning: "修订版", use: "报告、文章和教材" },
      { phrase: "an electronic version", meaning: "电子版", use: "出版和学习材料" },
    ],
    distinctions: [
      { word: "edition", difference: "edition 常指书籍或报刊的出版版本；version 可指软件、文件、电影等任何形式。", rule: "说 the latest version of an app，但说 the latest edition of a textbook。" },
    ],
    pitfalls: [
      { wrong: "the version of newest app", better: "the latest version of the app", why: "latest version 是自然且完整的表达。" },
    ],
    writingTip: "不要把 version 泛用于“观点”；观点常用 view 或 perspective。",
    speakingTip: "谈软件时 latest version 是高频实用搭配。",
    recall: "version = one form or update of something",
    answer: "Please install the latest version of the app.",
    productionFrame: "The latest version of ___ includes ___.",
  },
});

Object.assign(extendedCuratedProfiles, {
  therefore: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈðeəfɔː(r)/",
    cefr: "B2",
    level: "核心输出词",
    value: 88,
    skills: { reading: 90, listening: 70, task1: 64, task2: 96, speaking: 34 },
    coreMeaning: "因此；因为前述原因而产生后述结果。",
    definition: "for that reason; as a result",
    register: "正式书面语",
    topics: ["教育", "环境", "经济", "论证"],
    patterns: ["Therefore, + clause", "; therefore, + clause", "and therefore + verb phrase"],
    collocations: [
      { phrase: "therefore require action", meaning: "因此需要行动", use: "提出政策结论" },
      { phrase: "therefore result in sth", meaning: "因此导致某事", use: "说明逻辑后果" },
      { phrase: "and is therefore likely to + verb", meaning: "因此很可能……", use: "作审慎预测" },
    ],
    distinctions: [
      { word: "thus", difference: "thus 与 therefore 都正式；therefore 更明确地表示由前因推出后果。", rule: "therefore 前通常应有完整原因，常用分号或句号分隔。" },
    ],
    pitfalls: [
      { wrong: "Because costs rose, therefore prices increased.", better: "Costs rose; therefore, prices increased.", why: "because 和 therefore 不应同时承担同一因果连接功能。" },
    ],
    writingTip: "不要只用逗号连接两个完整句；用句号或分号更安全。",
    speakingTip: "口语中说 so 或 as a result 更自然。",
    recall: "therefore = for that reason",
    answer: "The scheme was too costly; therefore, it was abandoned.",
    productionFrame: "X is ___; therefore, Y ___.",
  },
  transform: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/trænsˈfɔːm/",
    cefr: "B2",
    level: "核心输出词",
    value: 84,
    skills: { reading: 88, listening: 70, task1: 70, task2: 90, speaking: 76 },
    coreMeaning: "使某物发生彻底、显著的改变。",
    definition: "to change something completely into a different form",
    register: "中性偏正式",
    topics: ["科技", "城市", "教育", "环境"],
    patterns: ["transform A into B", "be transformed by sth", "transform the way + clause"],
    collocations: [
      { phrase: "transform people's lives", meaning: "彻底改变人们的生活", use: "科技和社会影响" },
      { phrase: "transform a city", meaning: "改变一座城市的面貌", use: "城市发展话题" },
      { phrase: "be transformed by technology", meaning: "被技术改变", use: "描述长期变化" },
    ],
    distinctions: [
      { word: "change", difference: "change 可以很小；transform 强调深刻、根本的变化。", rule: "最稳妥结构是 transform A into B。" },
    ],
    pitfalls: [
      { wrong: "transform a city to a smart city", better: "transform a city into a smart city", why: "transform 常搭配 into 表示结果。" },
    ],
    writingTip: "只用于重大变化，避免用它描述小幅数字波动。",
    speakingTip: "可说 technology has transformed the way we communicate。",
    recall: "transform = change completely",
    answer: "Digital technology has transformed the way people work.",
    productionFrame: "___ has transformed the way people ___.",
  },
  board: {
    quality: 'curated',
    confidence: 4,
    ipaUk: "/bɔːd/",
    cefr: "B2",
    level: "核心理解词",
    value: 48,
    skills: { reading: 68, listening: 58, task1: 15, task2: 36, speaking: 45 },
    coreMeaning: "负责管理或监督一个机构的一组人。",
    definition: "a group of people who manage or supervise an organisation",
    register: "正式（管理义）；中性（物体义）",
    topics: ["商业", "教育", "工作", "管理"],
    patterns: ["serve on the board", "the board of directors", "a board meeting"],
    collocations: [
      { phrase: "board of directors", meaning: "董事会", use: "公司治理语境" },
      { phrase: "a board meeting", meaning: "董事会/理事会会议", use: "商业和机构新闻" },
      { phrase: "serve on the board", meaning: "担任理事会成员", use: "介绍职责或经历" },
    ],
    distinctions: [
      { word: "committee", difference: "board 往往是长期负责监督或管理的机构；committee 通常为特定任务而设。", rule: "作为成员说 serve on the board，不说 work in the board。" },
    ],
    pitfalls: [
      { wrong: "work in the board", better: "serve on the board", why: "表示担任管理成员时搭配 on the board。" },
    ],
    writingTip: "不要因正式而滥用；普通工作小组通常是 committee 或 team。",
    speakingTip: "若指学校管理机构，可先说明所在国家的制度。",
    recall: "board = governing group",
    answer: "She serves on the board of a local charity.",
    productionFrame: "The board decided to ___.",
  },
  create: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/kriˈeɪt/",
    cefr: "B1",
    level: "核心输出词",
    value: 95,
    skills: { reading: 92, listening: 90, task1: 62, task2: 90, speaking: 94 },
    coreMeaning: "制造新的事物；或使某种情况、机会或问题出现。",
    definition: "to make something new or cause something to happen",
    register: "中性",
    topics: ["工作", "科技", "文化", "经济"],
    patterns: ["create sth for sb", "create an opportunity to do sth", "create a need for sth"],
    collocations: [
      { phrase: "create jobs", meaning: "创造就业岗位", use: "经济和政策话题" },
      { phrase: "create opportunities for young people", meaning: "为年轻人创造机会", use: "教育和就业论证" },
      { phrase: "create a problem", meaning: "造成问题", use: "说明负面后果" },
    ],
    distinctions: [
      { word: "make", difference: "make 用途更广；create 更强调产生新事物或抽象结果。", rule: "说 make a decision，但说 create jobs/opportunities。" },
    ],
    pitfalls: [
      { wrong: "create a decision", better: "make a decision", why: "decision 的自然动词搭配是 make。" },
    ],
    writingTip: "create jobs 和 create opportunities 是安全搭配。",
    speakingTip: "谈爱好时可说 create content 或 create artwork。",
    recall: "create = make something new or cause it",
    answer: "Investment in public transport can create jobs.",
    productionFrame: "This policy could create ___ for ___.",
  },
  portion: {
    quality: 'curated',
    confidence: 4,
    ipaUk: "/ˈpɔːʃn/",
    cefr: "B2",
    level: "进阶理解词",
    value: 56,
    skills: { reading: 72, listening: 55, task1: 45, task2: 52, speaking: 60 },
    coreMeaning: "整体中的一部分、分得的一份，或一份食物。",
    definition: "a part or share of a whole, especially an amount of food",
    register: "中性",
    topics: ["饮食", "消费", "预算", "统计"],
    patterns: ["a portion of sth", "divide sth into portions", "allocate a portion of sth"],
    collocations: [
      { phrase: "a substantial portion of the budget", meaning: "预算中的很大一部分", use: "公共支出讨论" },
      { phrase: "portion size", meaning: "食物份量大小", use: "健康和饮食话题" },
      { phrase: "allocate a portion of funds", meaning: "分配部分资金", use: "政策和商业语境" },
    ],
    distinctions: [
      { word: "proportion", difference: "portion 是实际的一份或部分；proportion 是相对于整体的比例。", rule: "说 a large proportion of respondents，但说 a portion of the budget。" },
    ],
    pitfalls: [
      { wrong: "a large portion of students", better: "a large proportion of students", why: "谈统计人群比例时 proportion 更准确。" },
    ],
    writingTip: "Task 1 写百分比、占比时优先用 proportion。",
    speakingTip: "谈饮食时 portion size 是比 food amount 更自然的表达。",
    recall: "portion = a part or serving",
    answer: "A substantial portion of the budget is spent on health care.",
    productionFrame: "A large portion of ___ is allocated to ___.",
  },
  process: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈprəʊses/ (n.), /prəˈses/ (v.)",
    cefr: "B2",
    level: "Task 1 必备词",
    value: 95,
    skills: { reading: 93, listening: 85, task1: 100, task2: 74, speaking: 75 },
    coreMeaning: "按顺序进行的一系列步骤；也指按程序处理材料或数据。",
    definition: "a series of actions or stages that produce a result",
    register: "中性；技术和学术语境常用",
    topics: ["制造", "回收", "科技", "科学"],
    patterns: ["the process of doing sth", "be processed into sth", "a stage in the process"],
    collocations: [
      { phrase: "manufacturing process", meaning: "制造过程", use: "Task 1 流程图" },
      { phrase: "recycling process", meaning: "回收过程", use: "环境流程图" },
      { phrase: "data processing", meaning: "数据处理", use: "科技和工作话题" },
    ],
    distinctions: [
      { word: "procedure", difference: "process 是实际发生的一连串变化；procedure 是规定好的操作方法。", rule: "常说 the process of + 动名词。" },
    ],
    pitfalls: [
      { wrong: "the process of make paper", better: "the process of making paper", why: "of 后接动名词。" },
    ],
    writingTip: "首句总览流程，主体按阶段写，不必为每个箭头重复 process。",
    speakingTip: "解释步骤时搭配 first, then, after that。",
    recall: "process = stages leading to a result",
    answer: "The diagram shows the process of making paper.",
    productionFrame: "First, ___ is processed into ___, after which ___.",
  },
  signal: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈsɪɡnəl/",
    cefr: "B2",
    level: "核心输出词",
    value: 78,
    skills: { reading: 86, listening: 72, task1: 76, task2: 84, speaking: 65 },
    coreMeaning: "显示某事正在发生或可能发生的迹象、讯号；也指传递该讯号。",
    definition: "a sign or message that shows something is happening or likely to happen",
    register: "中性偏正式",
    topics: ["经济", "科技", "数据", "沟通"],
    patterns: ["signal that + clause", "signal a change/shift", "send a signal to sb"],
    collocations: [
      { phrase: "send a clear signal", meaning: "发出明确信号", use: "政策和沟通讨论" },
      { phrase: "signal a shift in policy", meaning: "显示政策转变", use: "新闻和议论文" },
      { phrase: "a warning signal", meaning: "警告信号", use: "风险和健康话题" },
    ],
    distinctions: [
      { word: "indicate", difference: "indicate 中性地表示证据所显示的内容；signal 更强调传递讯号、警示或变化。", rule: "动词 signal 直接接宾语，如 signal a change。" },
    ],
    pitfalls: [
      { wrong: "signal about a change", better: "signal a change", why: "signal 作动词时通常直接接所表示的内容。" },
    ],
    writingTip: "写图表时用 may signal，避免把推断写成确定因果。",
    speakingTip: "谈网络可说 a weak mobile signal。",
    recall: "signal = a sign that communicates something",
    answer: "The fall in sales may signal a change in consumer behaviour.",
    productionFrame: "This may signal a shift in ___.",
  },
  connection: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/kəˈnekʃn/",
    cefr: "B1",
    level: "核心输出词",
    value: 91,
    skills: { reading: 91, listening: 89, task1: 68, task2: 87, speaking: 91 },
    coreMeaning: "两个事物之间的联系、关系，或连接到网络/交通系统的方式。",
    definition: "a link or relationship between people, things, or ideas",
    register: "中性",
    topics: ["科技", "社会", "交通", "健康"],
    patterns: ["a connection between A and B", "a connection with/to sth", "make a connection between A and B"],
    collocations: [
      { phrase: "a direct connection between A and B", meaning: "A 与 B 的直接联系", use: "因果或科学讨论" },
      { phrase: "an internet connection", meaning: "网络连接", use: "科技和日常生活" },
      { phrase: "social connections", meaning: "社会关系/人脉", use: "社区和心理健康话题" },
    ],
    distinctions: [
      { word: "relationship", difference: "relationship 常指持续的人际或机构关系；connection 范围更广，也可指因果和技术联系。", rule: "最稳妥句型是 a connection between A and B。" },
    ],
    pitfalls: [
      { wrong: "the connection between A with B", better: "the connection between A and B", why: "between 固定与 and 搭配。" },
    ],
    writingTip: "若证据不足，用 possible connection，避免过度断言因果。",
    speakingTip: "可说 I have a poor internet connection at home。",
    recall: "connection = a link between things",
    answer: "Researchers found a connection between sleep and academic performance.",
    productionFrame: "There is a clear connection between ___ and ___.",
  },
  emotional: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ɪˈməʊʃənl/",
    cefr: "B2",
    level: "核心输出词",
    value: 78,
    skills: { reading: 84, listening: 72, task1: 20, task2: 83, speaking: 82 },
    coreMeaning: "与情感有关的；强烈表现或受情感影响的。",
    definition: "relating to feelings or showing strong feelings",
    register: "中性",
    topics: ["健康", "教育", "家庭", "媒体"],
    patterns: ["an emotional response to sth", "be emotional about sth", "provide emotional support for sb"],
    collocations: [
      { phrase: "emotional support", meaning: "情感支持", use: "家庭和心理健康议题" },
      { phrase: "emotional well-being", meaning: "情感福祉", use: "教育和健康写作" },
      { phrase: "an emotional response", meaning: "情绪反应", use: "媒体和经历描述" },
    ],
    distinctions: [
      { word: "emotive", difference: "emotional 指与情感有关或受情绪影响；emotive 指刻意引发情感的语言、画面等。", rule: "说 emotional support，但说 emotive language。" },
    ],
    pitfalls: [
      { wrong: "emotion support", better: "emotional support", why: "需要形容词 emotional 修饰 support。" },
    ],
    writingTip: "避免模糊的 emotional problems；尽量具体写 emotional well-being。",
    speakingTip: "谈电影或经历时可说 it was emotionally challenging。",
    recall: "emotional = related to feelings",
    answer: "Children need emotional support as well as academic guidance.",
    productionFrame: "___ can have a strong emotional impact on ___.",
  },
  rectangle: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈrek.tæŋ.ɡəl/",
    cefr: "A2",
    level: "理解优先词",
    value: 28,
    skills: { reading: 53, listening: 42, task1: 25, task2: 5, speaking: 36 },
    coreMeaning: "有四个直角的四边形。",
    definition: "a four-sided shape with four right angles",
    register: "基础几何；中性",
    topics: ["几何", "地图", "设计"],
    patterns: ["a rectangle with four right angles", "a rectangular shape", "the length and width of a rectangle"],
    collocations: [
      { phrase: "a rectangular shape", meaning: "长方形形状", use: "描述物体或布局" },
      { phrase: "a rectangle with four right angles", meaning: "有四个直角的长方形", use: "解释定义" },
      { phrase: "the length and width of a rectangle", meaning: "长方形的长和宽", use: "尺寸说明" },
    ],
    distinctions: [
      { word: "square", difference: "square 的四边都相等；rectangle 只要求四个角为直角。", rule: "数学上所有 square 都是 rectangle，但并非所有 rectangle 都是 square。" },
    ],
    pitfalls: [
      { wrong: "A rectangle has four equal sides.", better: "A rectangle has four right angles and two pairs of equal opposite sides.", why: "四边都相等是 square 的额外特征。" },
    ],
    writingTip: "Task 1 不必为显得高级而使用；形状准确比词汇复杂更重要。",
    speakingTip: "描述房间时 rectangular 比 rectangle 更常用。",
    recall: "rectangle = four right angles",
    answer: "The room is rectangular in shape.",
    productionFrame: "The ___ is rectangular, with ___.",
  },
  digital: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈdɪdʒɪtl/",
    cefr: "B2",
    level: "核心输出词",
    value: 92,
    skills: { reading: 91, listening: 84, task1: 61, task2: 95, speaking: 88 },
    coreMeaning: "与计算机、电子数据和数字技术有关的。",
    definition: "relating to computer technology or electronic data",
    register: "中性；学术常用",
    topics: ["科技", "教育", "媒体", "工作"],
    patterns: ["digital + noun", "go digital", "digital access to sth"],
    collocations: [
      { phrase: "digital technology", meaning: "数字技术", use: "科技发展讨论" },
      { phrase: "digital literacy", meaning: "数字素养", use: "教育和就业话题" },
      { phrase: "the digital divide", meaning: "数字鸿沟", use: "社会公平论证" },
    ],
    distinctions: [
      { word: "online", difference: "online 指连接互联网；digital 范围更广，包括离线电子设备和数字数据。", rule: "digital camera 可不联网；online course 必须通过网络。" },
    ],
    pitfalls: [
      { wrong: "digital informations", better: "digital information", why: "information 是不可数名词。" },
    ],
    writingTip: "digital divide 是讨论技术不平等的高价值搭配。",
    speakingTip: "可自然说 digital tools make learning more flexible。",
    recall: "digital = using computer-based technology",
    answer: "Digital literacy is increasingly important in the workplace.",
    productionFrame: "Digital technology can improve ___ by ___.",
  },
  global: {
    quality: 'curated',
    confidence: 5,
    ipaUk: "/ˈɡləʊbl/",
    cefr: "B2",
    level: "核心输出词",
    value: 90,
    skills: { reading: 92, listening: 84, task1: 72, task2: 94, speaking: 84 },
    coreMeaning: "与整个世界有关的；遍及全世界的。",
    definition: "relating to the whole world",
    register: "中性偏正式",
    topics: ["环境", "经济", "健康", "科技"],
    patterns: ["global + noun", "on a global scale", "a global approach to sth"],
    collocations: [
      { phrase: "global warming", meaning: "全球变暖", use: "环境话题" },
      { phrase: "the global economy", meaning: "全球经济", use: "贸易和就业讨论" },
      { phrase: "on a global scale", meaning: "在全球范围内", use: "强调影响范围" },
    ],
    distinctions: [
      { word: "international", difference: "international 指多个国家之间；global 指影响或覆盖整个世界。", rule: "仅涉及若干国家的合作可用 international，不必夸大为 global。" },
    ],
    pitfalls: [
      { wrong: "a global problem in the whole world", better: "a global problem", why: "global 已包含“全世界范围”的意思。" },
    ],
    writingTip: "不要把局部问题随意称为 global，以免论证失真。",
    speakingTip: "可说 climate change is a global concern。",
    recall: "global = worldwide",
    answer: "Climate change requires action on a global scale.",
    productionFrame: "___ is a global issue that requires ___.",
  },
  initiate: {
    quality: 'curated',
    confidence: 4,
    ipaUk: "/ɪˈnɪʃieɪt/",
    cefr: "C1",
    level: "进阶理解词",
    value: 64,
    skills: { reading: 78, listening: 55, task1: 15, task2: 80, speaking: 39 },
    coreMeaning: "有意地、正式地使一个行动、程序或讨论开始。",
    definition: "to cause a process or action to begin",
    register: "正式；学术和职业语境",
    topics: ["政策", "法律", "研究", "工作"],
    patterns: ["initiate sth", "initiate a process", "initiate discussions with sb"],
    collocations: [
      { phrase: "initiate reforms", meaning: "发起改革", use: "政府和制度话题" },
      { phrase: "initiate a dialogue", meaning: "启动对话", use: "冲突解决和合作" },
      { phrase: "initiate an investigation", meaning: "发起调查", use: "法律和新闻语境" },
    ],
    distinctions: [
      { word: "start", difference: "start 用途广且更口语；initiate 更正式，强调有计划地启动某项程序。", rule: "initiate 通常直接接名词宾语，不接 initiate to do。" },
    ],
    pitfalls: [
      { wrong: "initiate to reduce pollution", better: "initiate measures to reduce pollution", why: "initiate 需要具体发起的事物作宾语。" },
    ],
    writingTip: "Task 2 中 initiate reforms/measures 很自然，但不要为了高级而替换所有 start。",
    speakingTip: "普通经历用 start；谈官方项目时再用 initiate。",
    recall: "initiate = formally start something",
    answer: "The city initiated a programme to reduce traffic congestion.",
    productionFrame: "Authorities should initiate ___ to ___.",
  },
  kindergarten: {
    quality: 'curated',
    confidence: 4,
    ipaUk: "/ˈkɪndəɡɑːtn/",
    cefr: "B1",
    level: "理解优先词",
    value: 43,
    skills: { reading: 58, listening: 54, task1: 8, task2: 44, speaking: 61 },
    coreMeaning: "为进入小学前或小学初期儿童设置的学校或班级。",
    definition: "a school or class for young children before primary school",
    register: "中性；存在地区差异",
    topics: ["教育", "儿童", "家庭", "社会"],
    patterns: ["attend kindergarten", "go to kindergarten", "a kindergarten teacher"],
    collocations: [
      { phrase: "a kindergarten teacher", meaning: "幼儿园教师", use: "教育和职业话题" },
      { phrase: "attend kindergarten", meaning: "上幼儿园", use: "儿童成长描述" },
      { phrase: "a kindergarten class", meaning: "幼儿园班级", use: "学校场景" },
    ],
    distinctions: [
      { word: "nursery", difference: "nursery 和 kindergarten 的年龄与制度定义因国家而异；英国常见 nursery school，而 kindergarten 带有国际或北美色彩。", rule: "写作时按题目国家和教育制度选词；泛称可用 pre-school education。" },
    ],
    pitfalls: [
      { wrong: "go kindergarten", better: "go to kindergarten", why: "go 后表示去某机构时通常需要 to。" },
    ],
    writingTip: "国际性议论文中，pre-school education 比 kindergarten 更不受地区限制。",
    speakingTip: "谈本地教育制度时可先说明该词对应的年龄段。",
    recall: "kindergarten = early school for young children",
    answer: "Many children attend kindergarten before primary school.",
    productionFrame: "Children often attend kindergarten before ___.",
  },
});
